name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Run Unit Tests
      run: dotnet test --no-restore --verbosity normal --configuration Release
    - name: Publish to MyGet
      if: github.ref == 'refs/heads/master'
      run: dotnet nuget push src\**\*.nupkg -k ${{ secrets.MyGetApiKey }} -s https://www.myget.org/F/nuget-testing/api/v2/package --skip-duplicate
    
