name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      run: dotnet restore
    - name: Run GitVersion
      uses: roryprimrose/rungitversion@v1.0.0
  with:
    # "true" to use GitVersion /nofetch, any other value to enable fetch
    nofetch: "true" # default is false
    # "true" to use GitVersion /nocache, any other value to enable cache
    nocache: # default is false
    - name: List variables
      run: printenv | sort
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal --configuration Release
    - name: Add Package Repository Source
      run: dotnet nuget add source https://nuget.pkg.github.com/nhs-digital-gp-it-futures/index.json -n github -u nhs-digital-gp-it-futures -p ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text
    - name: Push to GitHub Packages
      run: dotnet nuget push src\**\*.nupkg --source github