name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      run: dotnet restore
    - uses: paulhatch/semantic-version@v2.1.1
      with:
        # The branch to count commits on
        branch: "master"
        # The prefix to use to identify tags
        tag_prefix: ""
        # A string which, if present in a git commit, indicates that a change represents a major (breaking) change
        major_pattern: "zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz"
        # Same as above except indicating a minor change
        minor_pattern: "master"
        # A string to determine the format of the version output
        format: "${major}.${minor}.${patch}-alpha.${increment}"
        # Path to check for changes. If any changes are detected in the path the 'changed' output will true. Enter multiple paths separated by spaces.
        change_path: "src"
    - name: List environment variables
      run: printenv | sort
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal --configuration Release
    - name: Add Package Repository Source
      run: dotnet nuget add source https://nuget.pkg.github.com/nhs-digital-gp-it-futures/index.json -n github -u nhs-digital-gp-it-futures -p ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text
    - name: Push to GitHub Packages
      run: dotnet nuget push src\**\*.nupkg --source github
